### ISSUE TITLE
Set Up Kanban Board Setup

### ISSUE THREAD

**Issue by Whoistolu** [chaw-bot/Ruby-Capstone-Project#34]
# Set Up Kanban Board Setup

- Link to project: https://github.com/chaw-bot/Ruby-Capstone-Project
- Team: A team of three(3) members
- Team member 1 - @ntzwilly 
- Team member 2 -  @chaw-bot 
- Team member 3 - @Whoistolu

**Comment by omar-labana** [comment]
Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to start it ☆*: .｡. o(≧▽≦)o .｡.:*☆ 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Whoistolu** [comment]
Hello [Omar](https://github.com/omar-labana),
Thank you for the feedback.
